language: android
sudo: required
jdk:
  - oraclejdk8
install: true
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "sudtanj"
  - git config --local user.email "sudono007@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
- provider: pages
  skip-cleanup: true
  github-token: 
    secure: "gv8odqUMRDLyQvuGAjOagQOxRcc2+8eN5BsQnuQwDlH86IOvQc4yFP9n/BPQ1HMIAbLpwVKofvy/2I4xZSIeSmmVxXBQp7NIVF+R7jsHurSubDRKoGQfE8UV+D15+8eFzHTXIcqWH3IL1WjfgLy7CVOJyl2a31Jibdqdr6nCQHs3nuvAi3OMUxVn04XKoZgLvGLPnz0Hogjt8bUVIHb+ZX2T+UJq4a4aoZj2l9mVTZGny/EMxoKjD884EphhLwWxSprgdk0OHP3SqqmoGbHYQCBP63kkfWSpIbsnzwYCdtqFaAU9hZM18ZDcLpVL8AuR0GIhaRpFe269KBXz8codOdCntMRwg+2/VZmOo7z8xm7MPyPhBxkv1BnhpmB4Mnpq2SjZ59pjW/X+oavF4Y2HFpIuI45ESx8Xj0dbf8RgMVNsIWwbzjJvhHklyTYFlhbYUkJ41j7wx9ju4SK8G9VjopxZwpnr4xfzFU+27SzuopJVXCx/iYxI8+Y4mNJ8KnQcFNDpGyXIzq1gMtLhvoHCqBLG/Np0wA1m4G6CG7FwLYgY3kiiS2dBuhgTyCFjPcf357Md9FmF+1Hn9k0B+se4M3g38tPOxbsconnXna0E98dxO1RSMuomJ873/JnMRbsiT5EDglSzn907ly8nyNEmW6M1NMkH422m9awHbeF4vwk="
  keep-history: false
  local-dir: "./javadoc"
  on:
    branch: gh-pages
 - provider: releases
  api_key: 
    secure: "gv8odqUMRDLyQvuGAjOagQOxRcc2+8eN5BsQnuQwDlH86IOvQc4yFP9n/BPQ1HMIAbLpwVKofvy/2I4xZSIeSmmVxXBQp7NIVF+R7jsHurSubDRKoGQfE8UV+D15+8eFzHTXIcqWH3IL1WjfgLy7CVOJyl2a31Jibdqdr6nCQHs3nuvAi3OMUxVn04XKoZgLvGLPnz0Hogjt8bUVIHb+ZX2T+UJq4a4aoZj2l9mVTZGny/EMxoKjD884EphhLwWxSprgdk0OHP3SqqmoGbHYQCBP63kkfWSpIbsnzwYCdtqFaAU9hZM18ZDcLpVL8AuR0GIhaRpFe269KBXz8codOdCntMRwg+2/VZmOo7z8xm7MPyPhBxkv1BnhpmB4Mnpq2SjZ59pjW/X+oavF4Y2HFpIuI45ESx8Xj0dbf8RgMVNsIWwbzjJvhHklyTYFlhbYUkJ41j7wx9ju4SK8G9VjopxZwpnr4xfzFU+27SzuopJVXCx/iYxI8+Y4mNJ8KnQcFNDpGyXIzq1gMtLhvoHCqBLG/Np0wA1m4G6CG7FwLYgY3kiiS2dBuhgTyCFjPcf357Md9FmF+1Hn9k0B+se4M3g38tPOxbsconnXna0E98dxO1RSMuomJ873/JnMRbsiT5EDglSzn907ly8nyNEmW6M1NMkH422m9awHbeF4vwk="
  file: "./app/build/outputs/apk/release/app-release.apk"
  skip_cleanup: true
  prerelease: true
after_success: 
  - find . -type f -printf "%T@ %p\n" | sort -nr | cut -d\  -f2-
env:
  global:
    secure: "Bsv5tIYdj/hCwbt0BVoxFyFStOBopco92ZnxvLCKfDTiPWgmLaKPC/E55OCr2cDJmjxM5xb+fDb6/VfR2QFuqC7yhIykpNu4Xt2loNBkINrj0H3SP+3KQFtfYSX//amypTR2+ChXjm3toc4a9sSlFu+qlppEJoOsAsPNSOA9YsYgnfU9PLkTRUNaUgFcFZzMgZRn7kvG94apk0Flq+uyp7DZ5dgRFA6I2ryMdiLJRs4W69rnffTuqNgoyEz3JUBfXKMSEDwFNnXMf+5g123hQ7z5OqnEKpBIDB35nMUrFbOUHLXH6buosVzxNOnHgXffnSy9hglx15aegTEeXlC3gGXlrHazCAkwV5+BESKFVtxxqV7K14rYuGUu9pqkwYal5cgwvJDz2fZa6ZQbSclrl2EjUNswKTuiYal3ifKfA5OI8SaV7Cyt9S6pUXV4NfsafiEJ4xHJFJdZ51TEH7eaKXLd1GBGTRdu4MaZzoAPQkBKkrZpZtm2lR+aPUPl6nTIPoYwzdv8s8xqw+MzOCdGJIQXcV1DeD2DSF7auLkYcBMwq+fa13w39wCe9+ckh/5b1UY8nG5ul3LtEcoI79HwV3Mdv+1YzV6nXix1i8ObtAgfbgNiq2E5L5/bXqJgD/HoCc+gVrsumA5VwYtNT0BAeI+iWErnZ/Op4FQhCACEd1k="
before_install:
  - yes | sdkmanager "platforms;android-27"
before_script:
  - chmod +x gradlew
script:
  - ./gradlew assembleRelease --stacktrace --info
  - ./gradlew doxygen
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.2

    # The SDK version used to compile your project
    - android-15

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-27
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-24
    - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-20
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-18
    - sys-img-armeabi-v7a-android-17
    - sys-img-armeabi-v7a-android-16
