language: android
sudo: required
jdk:
  - oraclejdk8
install: true
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
env:
  matrix:
    - API=android-26 ABI=armeabi-v7a
before_deploy:
  # Set up git user name and tag this commit
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: false
    local-dir: "./app/build/docs/javadoc/Release"
    target-branch: "gh-pages"
  - provider: releases
    api_key: 
      secure: "gv8odqUMRDLyQvuGAjOagQOxRcc2+8eN5BsQnuQwDlH86IOvQc4yFP9n/BPQ1HMIAbLpwVKofvy/2I4xZSIeSmmVxXBQp7NIVF+R7jsHurSubDRKoGQfE8UV+D15+8eFzHTXIcqWH3IL1WjfgLy7CVOJyl2a31Jibdqdr6nCQHs3nuvAi3OMUxVn04XKoZgLvGLPnz0Hogjt8bUVIHb+ZX2T+UJq4a4aoZj2l9mVTZGny/EMxoKjD884EphhLwWxSprgdk0OHP3SqqmoGbHYQCBP63kkfWSpIbsnzwYCdtqFaAU9hZM18ZDcLpVL8AuR0GIhaRpFe269KBXz8codOdCntMRwg+2/VZmOo7z8xm7MPyPhBxkv1BnhpmB4Mnpq2SjZ59pjW/X+oavF4Y2HFpIuI45ESx8Xj0dbf8RgMVNsIWwbzjJvhHklyTYFlhbYUkJ41j7wx9ju4SK8G9VjopxZwpnr4xfzFU+27SzuopJVXCx/iYxI8+Y4mNJ8KnQcFNDpGyXIzq1gMtLhvoHCqBLG/Np0wA1m4G6CG7FwLYgY3kiiS2dBuhgTyCFjPcf357Md9FmF+1Hn9k0B+se4M3g38tPOxbsconnXna0E98dxO1RSMuomJ873/JnMRbsiT5EDglSzn907ly8nyNEmW6M1NMkH422m9awHbeF4vwk="
    file: "./app/build/outputs/apk/release/app-release.apk"
    skip_cleanup: true
    prerelease: true
after_success: 
  - find . -type f -printf "%T@ %p\n" | sort -nr | cut -d\  -f2-
before_install:
  - yes | sdkmanager "platforms;$API"
before_script:
  - chmod u+x gradlew
  - android-update-sdk --components=sys-img-$ABI-$API --accept-licenses='android-sdk-license-[0-9a-f]{8}'
  - echo no | android create avd --force -n test -t $API --abi $ABI
  - emulator -avd test -no-audio -no-window
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew assembleRelease --stacktrace --info
  - ./gradlew generateReleaseJavadoc
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-15
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

