language: android
sudo: required
jdk:
  - oraclejdk8
install: true
addons:
  apt:
    packages:
env:
  matrix:
    - ANDROID_API=25 ANDROID_ABI=
    #- ANDROID_API=24 ANDROID_ABI=armeabi-v7a
    #- ANDROID_API=23 ANDROID_ABI=armeabi-v7a
    #- ANDROID_API=22 ANDROID_ABI=armeabi-v7a
    #- ANDROID_API=21 ANDROID_ABI=armeabi-v7a
    #- ANDROID_API=20 ANDROID_ABI=armeabi-v7a
    #- ANDROID_API=19 ANDROID_ABI=armeabi-v7a
    #- ANDROID_API=18 ANDROID_ABI=armeabi-v7a
    #- ANDROID_API=17 ANDROID_ABI=armeabi-v7a
    #- ANDROID_API=16 ANDROID_ABI=armeabi-v7a
before_deploy:
  # Set up git user name and tag this commit
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: false
    local-dir: "./app/build/docs/javadoc/Release"
    target-branch: "gh-pages"
  - provider: releases
    api_key: 
      secure: "gv8odqUMRDLyQvuGAjOagQOxRcc2+8eN5BsQnuQwDlH86IOvQc4yFP9n/BPQ1HMIAbLpwVKofvy/2I4xZSIeSmmVxXBQp7NIVF+R7jsHurSubDRKoGQfE8UV+D15+8eFzHTXIcqWH3IL1WjfgLy7CVOJyl2a31Jibdqdr6nCQHs3nuvAi3OMUxVn04XKoZgLvGLPnz0Hogjt8bUVIHb+ZX2T+UJq4a4aoZj2l9mVTZGny/EMxoKjD884EphhLwWxSprgdk0OHP3SqqmoGbHYQCBP63kkfWSpIbsnzwYCdtqFaAU9hZM18ZDcLpVL8AuR0GIhaRpFe269KBXz8codOdCntMRwg+2/VZmOo7z8xm7MPyPhBxkv1BnhpmB4Mnpq2SjZ59pjW/X+oavF4Y2HFpIuI45ESx8Xj0dbf8RgMVNsIWwbzjJvhHklyTYFlhbYUkJ41j7wx9ju4SK8G9VjopxZwpnr4xfzFU+27SzuopJVXCx/iYxI8+Y4mNJ8KnQcFNDpGyXIzq1gMtLhvoHCqBLG/Np0wA1m4G6CG7FwLYgY3kiiS2dBuhgTyCFjPcf357Md9FmF+1Hn9k0B+se4M3g38tPOxbsconnXna0E98dxO1RSMuomJ873/JnMRbsiT5EDglSzn907ly8nyNEmW6M1NMkH422m9awHbeF4vwk="
    file: "./app/build/outputs/apk/release/app-release.apk"
    skip_cleanup: true
    prerelease: true
after_success: 
  - find . -type f -printf "%T@ %p\n" | sort -nr | cut -d\  -f2-
  - adb push ./app/build/outputs/apk/release/app-release.apk /data/local/tmp/sud_tanj.com.phr_android
  - adb shell pm install -t -r "/data/local/tmp/sud_tanj.com.phr_android"
  - adb shell am start -n "sud_tanj.com.phr_android/sud_tanj.com.phr_android.GPlusLogin.Login" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-$ANDROID_API"
before_script:
  - chmod u+x gradlew
  - android list sdk --no-ui --all --extended
  - sdkmanager --list --verbose
  - android list targets
  - echo no | android create avd --force -n test -t android-$ANDROID_API --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
  - ./gradlew assembleRelease --stacktrace --info
  - ./gradlew generateReleaseJavadoc
android:
  components:
    - tools
    - tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - android-$ANDROID_API
    - sys-img-$ANDROID_ABI-google_apis-android-$ANDROID_API
    - build-tools-$ANDROID_API.0.1
    - platform-tools
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
