language: android
sudo: required
jdk:
  - oraclejdk8
install: true
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
env:
  matrix:
    - ANDROID_API_LEVEL=21 ANDROID_BUILD_TOOLS_VERSION=21.1.2 ANDROID_ABI=armeabi-v7a ANDROID_EMU_API_LEVEL=22 ADB_INSTALL_TIMEOUT=20 QEMU_AUDIO_DRV=none
before_deploy:
  # Set up git user name and tag this commit
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: false
    local-dir: "./app/build/docs/javadoc/Release"
    target-branch: "gh-pages"
  - provider: releases
    api_key: 
      secure: "gv8odqUMRDLyQvuGAjOagQOxRcc2+8eN5BsQnuQwDlH86IOvQc4yFP9n/BPQ1HMIAbLpwVKofvy/2I4xZSIeSmmVxXBQp7NIVF+R7jsHurSubDRKoGQfE8UV+D15+8eFzHTXIcqWH3IL1WjfgLy7CVOJyl2a31Jibdqdr6nCQHs3nuvAi3OMUxVn04XKoZgLvGLPnz0Hogjt8bUVIHb+ZX2T+UJq4a4aoZj2l9mVTZGny/EMxoKjD884EphhLwWxSprgdk0OHP3SqqmoGbHYQCBP63kkfWSpIbsnzwYCdtqFaAU9hZM18ZDcLpVL8AuR0GIhaRpFe269KBXz8codOdCntMRwg+2/VZmOo7z8xm7MPyPhBxkv1BnhpmB4Mnpq2SjZ59pjW/X+oavF4Y2HFpIuI45ESx8Xj0dbf8RgMVNsIWwbzjJvhHklyTYFlhbYUkJ41j7wx9ju4SK8G9VjopxZwpnr4xfzFU+27SzuopJVXCx/iYxI8+Y4mNJ8KnQcFNDpGyXIzq1gMtLhvoHCqBLG/Np0wA1m4G6CG7FwLYgY3kiiS2dBuhgTyCFjPcf357Md9FmF+1Hn9k0B+se4M3g38tPOxbsconnXna0E98dxO1RSMuomJ873/JnMRbsiT5EDglSzn907ly8nyNEmW6M1NMkH422m9awHbeF4vwk="
    file: "./app/build/outputs/apk/release/app-release.apk"
    skip_cleanup: true
    prerelease: true
after_success: 
  - find . -type f -printf "%T@ %p\n" | sort -nr | cut -d\  -f2-
before_install:
  #- yes | sdkmanager "platforms;$API"
before_script:
  - chmod u+x gradlew
  - android list sdk --extended --no-ui --all
  - sdkmanager --list --verbose
  - android list targets
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew assembleRelease --stacktrace --info
  - ./gradlew generateReleaseJavadoc
android:
  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - android-22
    - sys-img-armeabi-v7a-android-22 
    - build-tools-22.0.1
    - platform-tools
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
